# Generated by Django 2.2 on 2022-10-17 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 17, 19, 30, 58, 912435, tzinfo=utc),
                verbose_name="date published",
            ),
        ),
    ]
